server:
     port: 8888
     

    
    
spring:
    profiles:
        active:
         - test
          
    datasource:
          url: jdbc:mysql://localhost:3306/sahith
          username: root
          password: Sarezhtr@019
         
    application:
          name: This is the demo project for spring profiles
      